# .circleci/config.yml
version: 2
default: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: |
            npm install
            mkdir /tmp/artifacts;
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run backend tests
          command: |
            npm run test:server -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "/tmp/artifacts/js-test-results.xml"
      - run:
          name: Run frontend tests
          command: |
            npm run test:client -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "/tmp/artifacts/js-test-results.xml"
      - store_artifacts:
          path: /tmp/artifacts/js-test-results.xml
          destination: artifact-file
  deploy-auto:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Automation
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$AUTO_HEROKU_APP_NAME.git master --force
  deploy-test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Test
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$TEST_HEROKU_APP_NAME.git master --force
  deploy-prod:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Prod
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$PROD_HEROKU_APP_NAME.git master --force
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-auto:
          requires:
            - build
      - hold-deploy-test:
          type: approval
          requires:
            - deploy-auto
      - deploy-test:
          requires:
            - hold-deploy-test
      - hold-deploy-prod:
          type: approval
          requires:
            - deploy-test
      - deploy-prod:
          requires:
            - hold-deploy-prod
